# Generated by Django 4.1 on 2022-08-26 19:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0005_alter_snippet_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snippet',
            name='user',
        ),
        migrations.AddField(
            model_name='snippet',
            name='user',
            field=models.ManyToManyField(related_name='snippets', to=settings.AUTH_USER_MODEL),
        ),
    ]
