# Generated by Django 4.1 on 2022-08-27 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0006_remove_snippet_user_snippet_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='snippet',
            name='tag',
            field=models.ManyToManyField(related_name='snippets', to='snippets.tag'),
        ),
    ]
